version: '2.1'


services:
  revproxy:
    build:
      context: ./proxy
      args:
        - user=player1
        - pass=R34dy
    links:
      - "web:web"
    restart: always
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ="America/Chicago"
#    volumes:
#      - ./proxy/htpasswd:/etc/nginx/.htpasswd
#      - ./nginx.conf:/etc/nginx/nginx.conf
  web:
    build:
      context: ./web
    restart: always
    network_mode: bridge
    environment:
      - TZ="America/Chicago"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
